### ISSUE TITLE
npm 和 bower 的版本似乎并不同步？

### ISSUE THREAD

**Issue by tianyong90** [airyland/vux#201]
本人使用 bower 安装，但与 readme 中所示的当前 npm 版本不一致。

**Comment by airyland** [comment]
是不是0.0.117?

**Comment by tianyong90** [comment]
@airyland 对，bower的版本应该与 github 上的 tag 一致。但 github 上已经很久没发版了。

**Comment by airyland** [comment]
0.0.118是rc版本，没有打git tag, 所以bower没有更新。接下来版本是0.1了，中间应该不会有新的小版本了。

**Comment by tianyong90** [comment]
那这种情况下是不是该考虑把项目构建下更新，components里的东西十多天没动过了。我不用npm，本地自己构建时又各种报错（可能是环境问题），除了bower就只能直接克隆仓库了。

**Comment by airyland** [comment]
目前只有在发版本的时候才构建。不过你本地报错也不应该呀。

**Comment by airyland** [comment]
刚打了个v0.0.118的tag。

**Comment by tianyong90** [comment]
:+1:

**Comment by LiangFuzhi** [comment]
### Version 
0.0.117
### Android or iOS, which browser? 
 Android and iOS
### Your Codes 
用npm命令安装的vux里面的swiper组件代码有问题 
npm安装是这样的
`<template>
  <div class="slider">
    <div class="swiper" :style="swiperStyle">
      <slot></slot>
      <div class="item" v-for="item in list" @click="clickListItem(item)">
        <a :href="item.url">
          <div class="img" :style="{backgroundImage: buildBackgroundUrl(item.img)}"></div>
          <p class="desc">{{item.title}}</p>
        </a>
      </div>
    </div>
    <div class="indicator" v-show="show_dots && list.length > 1">
      <a href="javascript:" v-for="(index, item) in list">
        <i class="icon_dot" :class="{'active':index === current}"></i>
      </a>
    </div>
  </div>
</template>`
原版是
`<template>
  <div class="vux-slider">
    <div class="vux-swiper" :style="{height: xheight}">
      <slot></slot>
      <div class="vux-swiper-item" v-for="item in list" @click="clickListItem(item)">
        <a :href="item.url">
          <div class="vux-img" :style="{backgroundImage: buildBackgroundUrl(item.img)}"></div>
          <p class="vux-swiper-desc">{{item.title}}</p>
        </a>
      </div>
    </div>
    <div :class="['vux-indicator', 'vux-indicator-' + dotsPosition]" v-show="showDots && list.length > 1">
      <a href="javascript:" v-for="(index, item) in list">
        <i class="vux-icon-dot" :class="{'active':index === current}"></i>
      </a>
    </div>
  </div>
</template>`
所以使用后生成的代码
`<div class="slider" _v-7ddb9602=""> <div class="swiper" style="height: auto;">  <div class="item"> <a href="javascript:void(0)"> <div class="img" style="background-image: url(&quot;static/a48833af9331bfa3c782ba48a4cadfc9.jpg&quot;);"></div> <p class="desc">电产品类</p> </a> </div><div class="item"> <a href="javascript:void(0)"> <div class="img" style="background-image: url(&quot;static/5a88d2a8fa9de03ab24915d93a2a919b.jpg&quot;);"></div> <p class="desc">水产品类</p> </a> </div> </div> <div class="indicator"> <a href="javascript:"> <i class="icon_dot"></i> </a><a href="javascript:"> <i class="icon_dot active"></i> </a> </div> </div>`

显示是空白的
``` html
<!--put your code here-->
```

### Expected behavior and actual behavior.

### Steps to reproduce the problem

**Comment by airyland** [comment]
@LiangFuZhi 请另开issue，谢谢，在已关闭的issue里提交另一个问题很难管理追踪。

**Comment by LiangFuzhi** [comment]
@airyland 我这里不知道为什么提交问题的按钮是浅色的不可按状态
