### ISSUE TITLE
import {XAddress} from 'vux' 警告

### ISSUE THREAD

**Issue by mrzhouxu** [airyland/vux#2076]
![image](https://user-images.githubusercontent.com/21271032/31574122-5ae6372e-b0fb-11e7-9357-0b9cc605b733.png)

在源码里面 将scope改为slot-scope 就不报警告了。

不想改源码，有什么好的解决方案没有。vux 已经是最新版本

**Comment by airyland** [comment]
这是最新的 vue@2.5 导致的，直接改源码会导致旧版本挂掉。暂时只是警告不影响使用，我想一下怎么处理。

**Comment by Photokeep** [comment]
@airyland 这个warning问题目前还存在 请问怎么解决

**Comment by airyland** [comment]
@barray888 如果是 vux 源码的提示，更新 vux-loader

**Comment by Photokeep** [comment]
warning  in ./node_modules/vux/src/components/x-address/index.vue

(Emitted value instead of an instance of Error) the "scope" attribute for scoped slots have been deprecated and replaced by "slot-scope" since 2.5. The new "slot-scope" at
tribute can also be used on plain elements in addition to <template> to denote scoped slots.

 @ ./node_modules/vux/src/components/x-address/index.vue 6:0-453
 @ ./node_modules/babel-loader/lib!./node_modules/vux-loader/src/script-loader.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/views/manag
e-center/user-detail.vue
 @ ./src/views/manage-center/user-detail.vue
 @ ./src/views ^\.\/.*\.vue$
 @ ./src/router/_import_development.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

**Comment by Photokeep** [comment]
vux-loader已经是最新的 还是会提示warning

**Comment by airyland** [comment]
@barray888  帖个版本吧。

**Comment by suxinruolan** [comment]
![image](https://user-images.githubusercontent.com/41950146/52896694-36143f80-3206-11e9-8ade-63e5625bf14d.png)
老提示找不到css
