### ISSUE TITLE
建议： Picker组件联动时，数据第一列数据的parent值建议改为复杂字符串或可自定义

### ISSUE THREAD

**Issue by heaven2049** [airyland/vux#2589]
Picker组件联动情况下，data数组中第一列的parent值可为空 或 0 或者 '0'。

实际使用时，封装数据过程中可能出现parent为0的情况。（如以id为键构建数组，某节点的id恰好为0），那实际使用时需要特殊处理0的情况，略麻烦。

建议此默认值改为可通过props传递 |为空 | 一个较复杂字符串 表示第一列。

**Comment by xusenlin** [comment]
还是没有找到这个功能，我们返回的城市列表北京的关键code就是0，导致北京全部地区变父元素。父及留空也会导致子级parent为0时变父级的情况

**Comment by heaven2049** [comment]
> 还是没有找到这个功能，我们返回的城市列表北京的关键code就是0，导致北京全部地区变父元素。父及留空也会导致子级parent为0时变父级的情况

这个功能issue3月份提的，并没上线，个人对Vux不熟悉所以没有自行修改。

建议自行处理一下你的数据，比如赋值给Picker前code加一个前缀如：abcd_0，在实际保存时再移除前缀abcd_。

**Comment by xusenlin** [comment]
谢谢，是的，目前已经这么做了。 在2018年11月16日 12:27 ，Kyle写道： 还是没有找到这个功能，我们返回的城市列表北京的关键code就是0，导致北京全部地区变父元素。父及留空也会导致子级parent为0时变父级的情况 这个功能issue3月份提的，并没上线，个人对Vux不熟悉所以没有自行修改。 建议自行处理一下你的数据，比如赋值给Picker前code加一个前缀如：abcd_0，在实际保存时再移除前缀abcd_。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
