### ISSUE TITLE
clocker组件 on-finish倒计时结束后执行的方法失败，请问是写法有问题吗

### ISSUE THREAD

**Issue by Van-jue** [airyland/vux#659]
### PC网页
```html
<group title="Use in cell">
      <cell title="倒计时">
	  <clocker time="2016-11-15 15:15:25"  slots="value"  on-finish="finish()">
	  <span class="day">%_M1</span>
	  <span class="day">%_M2</span>分
          <span class="day">%_S1</span>
          <span class="day">%_S2</span>秒
	  </clocker>
      </cell>
    </group>   
```
```js
 <script>
     new Vue ({
         el: --,
         data:{},
         methods:{
             finish: function(){
                  console.log('this is a test');
             }
         }
     })
</script>
```
 理想的结果应该是倒计时结束在执行， 可是执行时程序执行时会先走 finish方法，请问是用法有问题吗？

**Comment by graysheeep** [comment]
on-finish = "finish"

**Comment by Van-jue** [comment]
我这样试了，也失败

**Comment by bigbigbigbear** [comment]
我写的on-finish方法也没有执行。
`<clocker :time="time" format="请在%M分%S秒内完成支付，超时将取消订单" @on-finish="hideCountDown" @on-tick="showCountDown = true"></clocker>`
#####方法如下
`hideCountDown: function(){
                this.showCountDown = false;
            }`


怎么解决呢

**Comment by qzltda** [comment]
在 2017-08-22 20:01:41，"Mr.Bear" <notifications@github.com> 写道：


我写的on-finish方法也没有执行。
<clocker :time="time" format="请在%M分%S秒内完成支付，超时将取消订单" @on-finish="hideCountDown" @on-tick="showCountDown = true"></clocker>
#####方法如下
hideCountDown: function(){ this.showCountDown = false; }

怎么解决呢

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.







你是

**Comment by yuyuFish** [comment]
我也遇到相同的问题了。请问有解决方法了吗
